BAT-288: removed req for git tag to publish Debian in do/publish (#13)
* BAT-288: removed req for git tag to publish Debian in do/publish

* BAT-288: update do/publish with new unique exit code

diff --git a/do/publish b/do/publish
--- a/do/publish
+++ b/do/publish
@@ -32,12 +32,6 @@ function publish_deb()
 {
   echo "--- :debian: Publish Debian file to APT Repo"
 
-  # make sure a git tag exists
-  if [[ -z "${GIT_VER_TAG-}" ]]; then
-    echo "No version tag on repo.  Nothing to do. Exiting early."
-    exit 0
-  fi
-
   # determine if there are uncommitted changes to tracked files
   if [[ -n $( git status --porcelain --untracked-files=no ) ]];  then
     echo "ERROR: Cannot publish Debian due to local changes to tracked files." >&2
@@ -71,8 +65,9 @@ function publish_deb()
 
   # make sure the Debian file doesn't already exist on the S3 bucket
   if [[ -n $( aws --region "${AWS_REGION}" s3 ls "${APT_REPOSITORY_URI}/${debian}" ) ]]; then
-    echo "ERROR: Cannot publish Debian.  File already exists in APT Repo (${APT_REPOSITORY_URI})." >&2
-    exit 1
+    echo "ERROR: Cannot publish ${debian}.  File already exists in APT Repo (${APT_REPOSITORY_URI})." >&2
+    # Specifically using a unique error code so we can soft fail in the pipeline when develop is re-run.
+    exit 123
   fi
 
   echo "Pushing '${debian}' to ${APT_REPOSITORY_URI}"
